services:
  ms-nisum-challenge:
    build: ./
    container_name: ms-nisum-crud-api
    environment:
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "8001:8001"
    networks:
      - spring_network
networks:
  spring_network:
    driver: bridge