logging:
  level:
    org:
      hibernate:
        SQL: debug
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: 1122q!
    driver-class-name: org.h2.Driver

app:
  init-sql: INSERT INTO UserEntity (id,name,email,password,isActive,token,createdAt,modified,lastLogin) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9)