server:
  servlet:
    context-path: /api/v1
  port: 8001

spring:
  profiles:
    active: local
  application:
    name: backend-template
  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true

#Actuator
management:
  endpoints:
    web:
      exposure:
        include:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      livenessstate:
        enabled: true
      readinessstate:
      enabled: true

#Project info
app:
  version: @project.version@
  name: @project.name@
